USE INVENTARIO;
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE table accounts_receivables; 
TRUNCATE table bar_codes; 
TRUNCATE table categories; 
TRUNCATE table client_credit; 
TRUNCATE table clients; 
TRUNCATE table costs; 
TRUNCATE table credit_types; 
TRUNCATE table debts; 
TRUNCATE table documents; 
TRUNCATE table documents_cash; 
TRUNCATE table inventory; 
TRUNCATE table invoice_details; 
TRUNCATE table invoices; 
TRUNCATE table migrations; 
TRUNCATE table movement_details; 
TRUNCATE table movements; 
TRUNCATE table movements_cash; 
TRUNCATE table password_resets; 
TRUNCATE table payment_methods; 
TRUNCATE table permission_role; 
TRUNCATE table permission_user; 
TRUNCATE table permissions; 
TRUNCATE table product_category; 
TRUNCATE table products; 
TRUNCATE table provider_product; 
TRUNCATE table providers; 
TRUNCATE table quotation_details; 
TRUNCATE table quotation_payment_methods; 
TRUNCATE table quotations; 
TRUNCATE table store_cash; 
SET FOREIGN_KEY_CHECKS=1;